### ISSUE TITLE
Addition to the README: step 3 for Windows10 users (-On how to get the required files )

### ISSUE THREAD

**Issue by thinking-0** [zaunkoenig-firmware/m1k-firmware#5]

**Comment by thinking-0** [comment]
Just install Linux on your Windows using it's WSL feature! (In my case I used Ubuntu.)
Then download and unzip the m1k-firmware-master.
(OR alternatively install git on Linux and download it using the git-clone https://github.com/zaunkoenig-firmware/m1k-firmware )
Then from the Linux terminal navigate to those files. Some help on how to here:
https://www.howtogeek.com/261383/how-to-access-your-ubuntu-bash-files-in-windows-and-your-windows-system-drive-in-bash/
Now follow the instructions from the file .travis.yml in order to get/compile the firmware
Now you can just follow the README on how to proceed.

**Comment by thinking-0** [comment]
Addition to the README: step 3 for Windows10 users (-On how to get the required files ):

Install Linux on your Windows 10 using it's WSL feature! (Use the Microsoft App Store searching for WSL and selecting one of the Linux distributions - in my case Ubuntu.)
Then download and unzip the m1k-firmware-master located here: 
https://github.com/zaunkoenig-firmware/m1k-firmware 
(more exact: download by pressing the green 'clone/download' button at the right top corner of the files list on the web page.)
Now run you Linux distribution from Windows opening the Linux Terminal.
Navigate to the downloaded firmware files by using following guide:
https://www.howtogeek.com/261383/how-to-access-your-ubuntu-bash-files-in-windows-and-your-windows-system-drive-in-bash/
Now follow the instructions from the file .travis.yml located in the unzipped firmware files in order to get/compile the required firmware files.

**Comment by patrick-schmalzried** [comment]
Created a pull request with updated instructions. Closing. Thanks @thinking-0. :)
